# Generated by Django 4.1.7 on 2023-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('date', models.DateField()),
                ('size', models.CharField(max_length=120)),
                ('extension', models.CharField(max_length=120)),
                ('filepath', models.TextField()),
            ],
        ),
    ]
